version: '3'

services:
  app:
    build: .
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/app/src:r

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./temp/data/pg:/var/lib/postgresql/data:rw

volumes:
  db-data:
